/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_comment = 2,
  anon_sym_AT = 3,
  sym_macro_body = 4,
  anon_sym_POUND = 5,
  sym_cmd_name = 6,
  sym_number = 7,
  sym_bare_string = 8,
  sym_quoted_string = 9,
  sym_array_ref = 10,
  sym_var_ref = 11,
  sym_double_ref = 12,
  sym_source_file = 13,
  sym_macro = 14,
  sym_command = 15,
  sym_arg = 16,
  aux_sym_source_file_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [anon_sym_AT] = "@",
  [sym_macro_body] = "macro_body",
  [anon_sym_POUND] = "#",
  [sym_cmd_name] = "cmd_name",
  [sym_number] = "number",
  [sym_bare_string] = "bare_string",
  [sym_quoted_string] = "quoted_string",
  [sym_array_ref] = "array_ref",
  [sym_var_ref] = "var_ref",
  [sym_double_ref] = "double_ref",
  [sym_source_file] = "source_file",
  [sym_macro] = "macro",
  [sym_command] = "command",
  [sym_arg] = "arg",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [anon_sym_AT] = anon_sym_AT,
  [sym_macro_body] = sym_macro_body,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_cmd_name] = sym_cmd_name,
  [sym_number] = sym_number,
  [sym_bare_string] = sym_bare_string,
  [sym_quoted_string] = sym_quoted_string,
  [sym_array_ref] = sym_array_ref,
  [sym_var_ref] = sym_var_ref,
  [sym_double_ref] = sym_double_ref,
  [sym_source_file] = sym_source_file,
  [sym_macro] = sym_macro,
  [sym_command] = sym_command,
  [sym_arg] = sym_arg,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_macro_body] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_cmd_name] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_var_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_double_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg1 = 1,
  field_arg2 = 2,
  field_body = 3,
  field_cmd = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg1] = "arg1",
  [field_arg2] = "arg2",
  [field_body] = "body",
  [field_cmd] = "cmd",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
  [1] =
    {field_cmd, 1},
  [2] =
    {field_arg1, 2},
    {field_cmd, 1},
  [4] =
    {field_arg2, 2},
    {field_cmd, 1},
  [6] =
    {field_arg1, 2},
    {field_arg2, 3},
    {field_cmd, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static const TSCharacterRange sym_cmd_name_character_set_1[] = {
  {'*', '+'}, {'-', '-'}, {'/', '1'}, {'<', '?'}, {'C', 'C'}, {'c', 'd'}, {'f', 'f'}, {'i', 'i'},
  {'k', 'l'}, {'n', 'p'}, {'r', 't'}, {'x', 'x'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '\n', 13,
        '"', 2,
        '#', 18,
        '$', 5,
        '%', 7,
        '*', 20,
        '@', 15,
        '_', 8,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (set_contains(sym_cmd_name_character_set_1, 12, lookahead)) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '$') ADVANCE(5);
      if (lookahead == '%') ADVANCE(7);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (set_contains(sym_cmd_name_character_set_1, 12, lookahead)) ADVANCE(19);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '@') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_macro_body);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_macro_body);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_cmd_name);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_cmd_name);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_array_ref);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_var_ref);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_double_ref);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_cmd_name] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_bare_string] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_array_ref] = ACTIONS(1),
    [sym_var_ref] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(13),
    [sym_macro] = STATE(2),
    [sym_command] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [anon_sym_AT] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 2,
      anon_sym_LF,
      sym_comment,
    STATE(4), 3,
      sym_macro,
      sym_command,
      aux_sym_source_file_repeat1,
  [19] = 3,
    ACTIONS(15), 1,
      anon_sym_LF,
    STATE(5), 1,
      sym_arg,
    ACTIONS(17), 6,
      sym_number,
      sym_bare_string,
      sym_quoted_string,
      sym_array_ref,
      sym_var_ref,
      sym_double_ref,
  [34] = 5,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 1,
      anon_sym_AT,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(21), 2,
      anon_sym_LF,
      sym_comment,
    STATE(4), 3,
      sym_macro,
      sym_command,
      aux_sym_source_file_repeat1,
  [53] = 3,
    ACTIONS(30), 1,
      anon_sym_LF,
    STATE(15), 1,
      sym_arg,
    ACTIONS(17), 6,
      sym_number,
      sym_bare_string,
      sym_quoted_string,
      sym_array_ref,
      sym_var_ref,
      sym_double_ref,
  [68] = 1,
    ACTIONS(32), 7,
      anon_sym_LF,
      sym_number,
      sym_bare_string,
      sym_quoted_string,
      sym_array_ref,
      sym_var_ref,
      sym_double_ref,
  [78] = 1,
    ACTIONS(34), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_AT,
      anon_sym_POUND,
  [86] = 1,
    ACTIONS(36), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_AT,
      anon_sym_POUND,
  [94] = 1,
    ACTIONS(38), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_AT,
      anon_sym_POUND,
  [102] = 1,
    ACTIONS(41), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_AT,
      anon_sym_POUND,
  [110] = 1,
    ACTIONS(43), 1,
      sym_macro_body,
  [114] = 1,
    ACTIONS(45), 1,
      sym_cmd_name,
  [118] = 1,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
  [122] = 1,
    ACTIONS(49), 1,
      anon_sym_LF,
  [126] = 1,
    ACTIONS(51), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 19,
  [SMALL_STATE(4)] = 34,
  [SMALL_STATE(5)] = 53,
  [SMALL_STATE(6)] = 68,
  [SMALL_STATE(7)] = 78,
  [SMALL_STATE(8)] = 86,
  [SMALL_STATE(9)] = 94,
  [SMALL_STATE(10)] = 102,
  [SMALL_STATE(11)] = 110,
  [SMALL_STATE(12)] = 114,
  [SMALL_STATE(13)] = 118,
  [SMALL_STATE(14)] = 122,
  [SMALL_STATE(15)] = 126,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 3, 0, 1),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 2),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_command, 4, 0, 3), REDUCE(sym_command, 4, 0, 4),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 5, 0, 5),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [47] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lo3(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
